swagger: '2.0'
info:
  title: FRW - API
  description: Définition de l'API publique pour intéragir avec FRW.
  contact:
    name: MESS - SFPS
  version: v1
paths:
  /api/v1/Document/Telecharger/{nomFichierProtege}:
    get:
      tags:
        - Document
      summary: FRW121 - Télécharger une pièce par nom de fichier protégé
      description: Permet de récupérer une pièce jointe transmise par un citoyen
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: path
          name: nomFichierProtege
          description: Nom fichier protégé (provient du contenu du formulaire)
          required: true
          type: string
        - in: query
          name: bypassSecurite
          description: Permet de ne pas valider la sécurité.
          type: boolean
          default: false
        - in: header
          name: X-NoPublicSystemeAutorise
          description: Guid publique de système autorisé
          type: string
        - in: header
          name: X-ApiKey
          description: Clée API
          type: string
      responses:
        '200':
          description: Succès
        '400':
          description: Paramètre manquant ou invalide
          schema:
            $ref: '#/definitions/ProblemDetails'
        '401':
          description: Accès non autorisé
          schema:
            $ref: '#/definitions/ProblemDetails'
        '404':
          description: Fichier demandé introuvable
          schema:
            $ref: '#/definitions/ProblemDetails'
        '500':
          description: Paramètre manquant, invalide ou erreur interne du serveur
      security:
        - ApiKey: []
        - NoPublicSystemeAutorise: []
  /api/v1/SIS/CreerFormulaireIndividu/{typeFormulaire}:
    post:
      tags:
        - SIS
      summary: FRW111 - Créer un formulaire Web pour un individu.
      description: Permet de créer un formulaire pour un individu connu par le système autorisé.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: typeFormulaire
          description: _Exemple:_ `3003`
          required: true
          type: string
        - in: header
          name: X-ApiKey
          description: Clé Api
          type: string
        - in: header
          name: X-NoPublicSystemeAutorise
          description: Numéro public du système autorisé
          type: string
        - in: header
          name: X-IdentifiantUtilisateur
          description: Identifiant de l'utilisateur
          type: string
        - in: body
          name: body
          description: 'Le contenu du formulaire (pour pré-remplissage) ex: `{"form": {"champ1": "val1"} }`'
          schema: {}
      responses:
        '200':
          description: Succès
          schema:
            $ref: '#/definitions/RetourCreerReprendreFormulaireIndividu'
        '400':
          description: Paramètre manquant ou invalide
          schema:
            $ref: '#/definitions/ProblemDetails'
        '401':
          description: Accès non autorisé
          schema:
            $ref: '#/definitions/ProblemDetails'
        '500':
          description: Paramètre manquant, invalide ou erreur interne du serveur
      security:
        - ApiKey: []
        - NoPublicSystemeAutorise: []
  /api/v1/SIS/ObtenirFormulairesIndividu:
    post:
      tags:
        - SIS
      summary: FRW112 - Obtenir la liste des formulaires Web d'un individu
      description: Permet d'obtenir tous les formulaires d'un individu selon les états passés en paramètres.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: X-ApiKey
          description: Clé Api
          type: string
        - in: header
          name: X-NoPublicSystemeAutorise
          description: Numéro public du système autorisé
          type: string
        - in: header
          name: X-IdentifiantUtilisateur
          description: Identifiant de l'utilisateur
          type: string
        - in: body
          name: body
          description: Objet de critères de recherche
          schema:
            $ref: '#/definitions/EntrantRechercherFormulairesSIS'
      responses:
        '200':
          description: Succès
          schema:
            type: array
            items:
              $ref: '#/definitions/RetourRechercherFormulaires'
        '400':
          description: Paramètre manquant ou invalide
          schema:
            $ref: '#/definitions/ProblemDetails'
        '401':
          description: Accès non autorisé
          schema:
            $ref: '#/definitions/ProblemDetails'
        '500':
          description: Paramètre manquant, invalide ou erreur interne du serveur
      security:
        - ApiKey: []
        - NoPublicSystemeAutorise: []
  /api/v1/SIS/ObtenirIdentifiantSessionFormulaire/{noFormulairePublic}:
    post:
      tags:
        - SIS
      summary: FRW113 - Obtenir un identifiant de session pour un formulaire
      description: Permet de reprendre un formulaire pour un utilisateur le demandant
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: noFormulairePublic
          description: Identifiant du formulaire pour lequel créer une session
          required: true
          type: string
        - in: header
          name: X-ApiKey
          description: Clé Api
          type: string
        - in: header
          name: X-NoPublicSystemeAutorise
          description: Numéro public du système autorisé
          type: string
        - in: header
          name: X-IdentifiantUtilisateur
          description: Identifiant de l'utilisateur
          type: string
        - in: body
          name: body
          description: Contenu à remplacer dans le formulaire à reprendre (Ne permet que de remplacer un contexte ou un objet perso. ne remplace pas le contenu d'un formulaire.)
          schema: {}
      responses:
        '200':
          description: Succès
          schema:
            $ref: '#/definitions/RetourCreerReprendreFormulaireIndividu'
        '400':
          description: Paramètre manquant ou invalide
          schema:
            $ref: '#/definitions/ProblemDetails'
        '401':
          description: Accès non autorisé
          schema:
            $ref: '#/definitions/ProblemDetails'
        '500':
          description: Paramètre manquant, invalide ou erreur interne du serveur
      security:
        - ApiKey: []
        - NoPublicSystemeAutorise: []
  /api/v1/SIS/SupprimerFormulaire/{noFormulairePublic}:
    get:
      tags:
        - SIS
      summary: FRW114 - Supprimer un formulaire web
      description: Permet de supprimer un formulaire demandé
      produces:
        - application/json
      parameters:
        - in: path
          name: noFormulairePublic
          description: Identifiant du formulaire à supprimer
          required: true
          type: string
        - in: header
          name: X-ApiKey
          description: Clé Api
          type: string
        - in: header
          name: X-NoPublicSystemeAutorise
          description: Numéro public du système autorisé
          type: string
        - in: header
          name: X-IdentifiantUtilisateur
          description: Identifiant de l'utilisateur
          type: string
      responses:
        '200':
          description: Succès
        '400':
          description: Paramètre manquant ou invalide
          schema:
            $ref: '#/definitions/ProblemDetails'
        '401':
          description: Accès non autorisé
          schema:
            $ref: '#/definitions/ProblemDetails'
        '500':
          description: Paramètre manquant, invalide ou erreur interne du serveur
      security:
        - ApiKey: []
        - NoPublicSystemeAutorise: []
definitions:
  EntrantRechercherFormulairesSIS:
    type: object
    properties:
      etatsFormulaireRecherche:
        type: array
        items:
          type: string
      codeTypeFormulaire:
        type: string
      noConfirmation:
        format: int32
        type: integer
      noPublicFormulaire:
        type: string
  ProblemDetails:
    type: object
    properties:
      type:
        type: string
      title:
        type: string
      status:
        format: int32
        type: integer
      detail:
        type: string
      instance:
        type: string
    additionalProperties: {}
  RetourCreerReprendreFormulaireIndividu:
    type: object
    properties:
      noPublicSession:
        type: string
      noPublicForm:
        type: string
  RetourRechercherFormulaires:
    type: object
    properties:
      typeFormulaire:
        type: string
      noPublicForm:
        type: string
      identifiantUtilisateur:
        type: string
      titreFrancais:
        type: string
      titreAnglais:
        type: string
      dateCreation:
        format: date-time
        type: string
      dernierEtat:
        type: string
      dateDernierEtat:
        format: date-time
        type: string
      dateEpuration:
        format: date-time
        type: string
      numeroConfirmation:
        format: int32
        type: integer
securityDefinitions:
  ApiKey:
    type: apiKey
    name: X-ApiKey
    in: header
    description: Clée API secrète du système autorisé
  NoPublicSystemeAutorise:
    type: apiKey
    name: X-NoPublicSystemeAutorise
    in: header
    description: Numéro public du système autorisé
