# Pour générer le fichier .md : npx swagger-markdown -i .\FRW.API.yml -o .\README.md
swagger: '2.0'
info:
  title: FRW - API
  description: Définition de l'API publique pour intéragir avec FRW.
paths:
  /api/v1/Document/Telecharger/{nomFichierProtege}:
    get:
      tags:
        - Document
      summary: FRW121 - Télécharger une pièce par nom de fichier protégé
      produces:
        - text/plain
        - application/json
        - text/json
      example: TEST
      parameters:
        - in: path
          name: nomFichierProtege
          description: Nom fichier protégé (provient du contenu du formulaire)
          required: true
          type: string
        - in: header
          name: X-NoPublicSystemeAutorise
          description: Guid publique de système autorisé
          required: true
          type: string
        - in: header
          name: X-ApiKey
          required: true
          description: Clée API
          type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
  /api/v1/SIS/CreerFormulaireIndividu/{typeFormulaire}:
    post:
      tags:
        - SIS
      summary: FRW111 - Créer un formulaire Web pour un individu.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: typeFormulaire
          description: '_Example:_ `"3003"`'
          required: true
          type: string
          example: '3003'
        - in: header
          name: X-ApiKey
          description: Clé Api
          required: true
          type: string
        - in: header
          name: X-NoPublicSystemeAutorise
          description: Numéro public du système autorisé
          required: true
          type: string
        - in: header
          name: X-IdentifiantUtilisateur
          description: Identifiant de l'utilisateur pour lequel le formulaire est créé
          type: string
        - in: body
          name: body
          description: ''
          schema:
            $ref: '#/definitions/EntrantCreerFormulaireIndividu'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/RetourCreerReprendreFormulaireIndividu'
  /api/v1/SIS/ObtenirFormulairesIndividu:
    post:
      tags:
        - SIS
      summary: FRW112 - Obtenir les formulaire web d'un individu
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: X-ApiKey
          required: true
          description: Clé Api
          type: string
        - in: header
          name: X-NoPublicSystemeAutorise
          required: true
          description: Numéro public du système autorisé
          type: string
        - in: header
          name: X-IdentifiantUtilisateur
          description: Identifiant de l'utilisateur pour lequel obtenir les formulaires
          type: string
        - in: body
          name: body
          description: ''
          schema:
            $ref: '#/definitions/EntrantRechercherFormulairesSIS'
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/RetourRechercherFormulaires'
  /api/v1/SIS/ObtenirIdentifiantSessionFormulaire/{noFormulairePublic}:
    post:
      tags:
        - SIS
      summary: FRW113 - Obtenir un identifiant de session pour un formulaire
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: noFormulairePublic
          description: Identifiant du formulaire pour lequel créer une session
          required: true
          type: string
        - in: header
          name: X-ApiKey
          required: true
          description: Clé Api
          type: string
        - in: header
          name: X-NoPublicSystemeAutorise
          required: true
          description: Numéro public du système autorisé
          type: string
        - in: header
          name: X-IdentifiantUtilisateur
          description: Identifiant de l'utilisateur pour lequel on demande une session
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/RetourCreerReprendreFormulaireIndividu'
  /api/v1/SIS/SupprimerFormulaire/{noFormulairePublic}:
    get:
      tags:
        - SIS
      summary: FRW114 - Supprimer un formulaire web
      parameters:
        - in: path
          name: noFormulairePublic
          description: Identifiant du formulaire à supprimer
          required: true
          type: string
        - in: header
          name: X-ApiKey
          description: Clé Api
          type: string
        - in: header
          name: X-NoPublicSystemeAutorise
          description: Numéro public du système autorisé
          type: string
        - in: header
          name: X-IdentifiantUtilisateur
          description: Identifiant de l'utilisateur
          type: string
      responses:
        '200':
          description: Success
  /api/v1/SIS/DeployerSysteme:
    post:
      tags:
        - SIS
      summary: FRWxxx - Déployer un système au complet
      consumes:
        - application/json
      parameters:
        - in: header
          name: X-ApiKey
          required: true
          description: Clé Api
          type: string
        - in: header
          name: X-NoPublicSystemeAutorise
          required: true
          description: Numéro public du système autorisé
          type: string
        - in: body
          name: body
          schema:
            $ref: '#/definitions/EntrantDeployerSysteme'
      responses:
        '200':
          description: Success
definitions:
  EntrantCreerFormulaireIndividu:
    type: object
    properties:
      form:
        type: object
        description: Le contenu du formulaire (pour pré-remplissage)
      ..AUTRES..:
        type: object
        description: N'importe quelles autres propriétés, vous pouvez choisir les noms à votre guise.
  EntrantDeployerSysteme:
    type: object
    properties:
      zip:
        format: byte
        type: string
  EntrantRechercherFormulairesSIS:
    type: object
    properties:
      etatsFormulaireRecherche:
        type: array
        description: Liste des états à obtenir
        items:
          type: string
        example:
        - foo
        - bar
        - baz
      codeTypeFormulaire:
        type: string
        description: Code du formualaire ex. `3003`
      noConfirmation:
        format: int32
        type: integer
      noPublicFormulaire:
        type: string
  RetourCreerReprendreFormulaireIndividu:
    type: object
    properties:
      noPublicSession:
        type: string
      noPublicForm:
        type: string
  RetourRechercherFormulaires:
    type: object
    properties:
      typeFormulaire:
        type: string
        example: 3003
      noPublicForm:
        type: string
        description: Identifiant unique du formulaire
      identifiantUtilisateur:
        type: string
        description: Identifiant de l'utilisateur à qui appartient le formulaire
      titreFrancais:
        type: string
        description: Titre français du formulaire extrait de la configuation
      titreAnglais:
        type: string
        description: Titre anglais du formulaire extrait de la configuation
      dateCreation:
        format: date-time
        description: Date de création du formulaire
        type: string
      dernierEtat:
        type: string
        description: Dernier état
        example: MAJ
      dateDernierEtat:
        format: date-time
        description: Date de la dernière modification ou ouverture du formulaire
        type: string
