# This is a basic workflow to help you get started with Actions
name: Build

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        folder-path: 'Documentation'
        config-file: '.github/workflows/mlc_config.json'
        file-path: './README.md'
